### PR TITLE
fix: ignore query string when interpreting identifiers

### LINKED ISSUE #122: [BUG] interpretIdentifier does not handle versionId
The helper method that interprets an identifier should strip away the querystring

**Expected**
```typescript
const { address } = interpretIdentifier("did:ethr:0xd0dbe9d3698738f899ccd8ee27ff2347a7faa4dd?versionId=42")
expect(address).toEqual('0xd0dbe9d3698738f899ccd8ee27ff2347a7faa4dd')
```

**Actual**
```typescript
// invalid arrayify value (argument="value", value="0xd0dbe9d3698738f899ccd8ee27ff2347a7faa4dd?versionId=42", code=INVALID_ARGUMENT, version=bytes/5.1.0)
```

### PR DESCRIPTION
**Pull request by mirceanis**
fixes #122

Most of the PR is adding extra tests, the actual change is [on this line](https://github.com/decentralized-identity/ethr-did-resolver/pull/123/files#r616669845)

Background:
`interpretIdentifier()` is a helper method that is supposed to split a string into components
In case one of the components is a public key, to also compute the address.
In case the string is a DID, it should try to extract the network identifier section of it as well, and discard any query string

### CODE REVIEW

File: src/helpers.ts [hunk 1]
```diff
@@ -95,6 +95,7 @@ export function interpretIdentifier(identifier: string): { address: string; publ
   let id = identifier
   let network = undefined
   if (id.startsWith('did:ethr')) {
+    id = id.split('?')[0]
```
Comment (mirceanis) [inline src/helpers.ts:98]: This is the actual change

File: src/__tests__/extended-id.test.ts [hunk 2]
```diff
@@ -37,3 +37,88 @@ describe('pattern matcher', () => {
...
+
+describe('interpretIdentifier', () => {
+  const pubKey = '0x02b97c30de767f084ce3080168ee293053ba33b235d7116a3263d29f1450936b71'
+  const checksumAddress = '0xC662e6c5F91B9FcD22D7FcafC80Cf8b640aed247'
+
+  it('parses ethereumAddress', () => {
+    const { address, publicKey, network } = interpretIdentifier(checksumAddress.toLowerCase())
+    expect(address).toEqual(checksumAddress)
+    expect(publicKey).toBeUndefined()
+    expect(network).toBeUndefined()
```
Comment (awoie) [inline src/__tests__/extended-id.test.ts:49]: why is this undefined? shouldn't it be mainnet? applies to the other tests as well.

File: src/__tests__/extended-id.test.ts [hunk 3]
```diff
@@ -37,3 +37,88 @@ describe('pattern matcher', () => {
...
+  it('parses did:ethr with address and sub-network', () => {
+    const { address, publicKey, network } = interpretIdentifier(`did:ethr:rsk:testnet:${checksumAddress}`)
+    expect(address).toEqual(checksumAddress)
+    expect(publicKey).toBeUndefined()
+    expect(network).toEqual('rsk:testnet')
+  })
+  it('parses did:ethr with address and sub-network and version', () => {
+    const { address, publicKey, network } = interpretIdentifier(`did:ethr:rsk:testnet:${checksumAddress}?versionId=42`)
+    expect(address).toEqual(checksumAddress)
+    expect(publicKey).toBeUndefined()
```
Comment (awoie) [inline src/__tests__/extended-id.test.ts:84]: well, hard to check whether this is correct.

File: src/__tests__/networks.integration.test.ts [hunk 4]
```diff
@@ -9,14 +9,45 @@ describe('ethrResolver (alt-chains)', () => {
...
-  describe('eth-testnets', () => {
-    it('resolves on ropsten when configured', () => {
+  describe('eth-networks', () => {
+    it('resolves on mainnet with versionId', async () => {
+      const resolver = new Resolver(getResolver({ infuraProjectId: '6b734e0b04454df8a6ce234023c04f26' }))
+      const result = await resolver.resolve('did:ethr:0x26bf14321004e770e7a8b080b7a526d8eed8b388?versionId=12090174')
+      expect(result).toEqual({
+        didDocumentMetadata: {
+          nextVersionId: '12090175',
+          nextUpdate: '2021-03-22T18:14:29.000Z',
```
Comment (awoie) [inline src/__tests__/networks.integration.test.ts:19]: milliseconds should be dropped --> 2021-03-22T18:14:29Z

File: src/__tests__/networks.integration.test.ts [hunk 5]
```diff
@@ -9,14 +9,45 @@ describe('ethrResolver (alt-chains)', () => {
...
+        },
+        didResolutionMetadata: {
+          contentType: 'application/did+ld+json',
+        },
+        didDocument: {
+          '@context': [
+            'https://www.w3.org/ns/did/v1',
+            'https://identity.foundation/EcdsaSecp256k1RecoverySignature2020/lds-ecdsa-secp256k1-recovery2020-0.0.jsonld',
```
Comment (awoie) [inline src/__tests__/networks.integration.test.ts:27]: at some point we should fix that and use a shorter url but this is wip

File: src/__tests__/networks.integration.test.ts [hunk 6]
```diff
@@ -9,14 +9,45 @@ describe('ethrResolver (alt-chains)', () => {
...
+          id: 'did:ethr:0x26bf14321004e770e7a8b080b7a526d8eed8b388',
+          verificationMethod: [
+            {
+              id: 'did:ethr:0x26bf14321004e770e7a8b080b7a526d8eed8b388#controller',
+              type: 'EcdsaSecp256k1RecoveryMethod2020',
+              controller: 'did:ethr:0x26bf14321004e770e7a8b080b7a526d8eed8b388',
+              blockchainAccountId: '0x26bF14321004e770E7A8b080b7a526d8eed8b388@eip155:1',
+            },
+          ],
+          authentication: ['did:ethr:0x26bf14321004e770e7a8b080b7a526d8eed8b388#controller'],
```
Comment (awoie) [inline src/__tests__/networks.integration.test.ts:38]: shouldn't this also include `assertionMethod` now?

**Review by awoie — CHANGES_REQUESTED** [review]
lgtm, milliseconds should be dropped imo but might be a separate PR. some other things are not entirely clear re network if no network part but i guess that should be fine.

File: src/__tests__/extended-id.test.ts (hunk 2 above)
Comment (mirceanis) [reply src/__tests__/extended-id.test.ts:49]: yeah, perhaps I should have been more clear about the intent of this method.
It's a helper method that needs to split a string into components, and in case one of the components is a public key, to also compute the address.

The logic to decide whether the network is mainnet when not specified is in a different part of the code.

So, in the general case, yes, it should be mainnet, but not for this method. Here it's expected to not be defined.

File: src/__tests__/extended-id.test.ts (hunk 3 above)
Comment (mirceanis) [reply src/__tests__/extended-id.test.ts:84]: what do you mean?
what is at risk of not being correct?

File: src/__tests__/networks.integration.test.ts (hunk 4 above)
Comment (mirceanis) [reply src/__tests__/networks.integration.test.ts:19]: correct.
but that is going to be part of a different PR

File: src/__tests__/networks.integration.test.ts (hunk 5 above)
Comment (mirceanis) [reply src/__tests__/networks.integration.test.ts:27]: I fully agree!

File: src/__tests__/networks.integration.test.ts (hunk 6 above)
Comment (mirceanis) [reply src/__tests__/networks.integration.test.ts:38]: right. once I rebase this on to the latest changes, it will be.
good catch!

Comment (mirceanis) [reply src/__tests__/networks.integration.test.ts:38]: done

**Review by awoie — APPROVED** [review]
lgtm
